title: Image Cropping under Design Constraints
description: 
show_downloads: true
github:
  pub_url: https://arxiv.org/abs/2310.08892
  paper_url: https://arxiv.org/abs/2310.08892 
  code_url: https://github.com/CyberAgentAILab/image_cropping_under_design_constraints
theme: jekyll-theme-cayman